title: Zeno's digital garden
repository: gramer/gramer.github.io
email: gramer2188@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: gramer.github.io
github_username:  gramer
include: [ '_pages' ]
exclude:
  - _includes/notes_graph.json
  - _notes/Kakaopay/*
  - _notes/Personal/*
  - .idea
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# If you are using a host that cannot resolve URLs that do
# not end with .html (such as Neocities), set this to 'true'.
use_html_extension: false

# Set to `true` to open non-internal links in new tabs, or
# set to `false` to open non-internal links in current tab.
open_external_links_in_new_tab: true

# Set to `true` to replace tweet URLs with Twitter embeds.
# Note that doing so will negatively the reader's privacy
# as their browser will communicate with Twitter's servers.
embed_tweets: false

permalink: pretty
relative_permalinks: false
safe: true

plugins:
  - jekyll-last-modified-at
  - jekyll-toc
  - jekyll-mermaid

sass:
  sass_dir: _sass
  style: :compressed

collections:
  notes:
    output: true
    permalink: /:slug

defaults:
  - scope:
      path: "**/*"
    values:
      layout: "default"
  - scope:
      path: "_notes/**/*.md"
    values:
      layout: "note"
      toc: true
